### PR TITLE
Added missing payload fields

### PR DESCRIPTION
**Pull request by kkocel**

### CODE REVIEW

**Comment by kkocel** [comment]
Cla signed

**Comment by jfschmakeit** [comment]
Thanks for your pull request!

Good catch with the missing payload fields, that's a great addition! 

At this point, let's keep the AttestationResult classes separate, even though they contain the same fields. We are using the class differently in OnlineVerify and OfflineVerify. 
In the offline sample, we are using it to parse a  a JsonWebSignature payload directly (hence the need to extend JsonWebSignature.Payload), whereas for the online sample, we are simply parsing the JSON response. The idea is to show both ways of interacting with the response, that's why I think we should keep them small and self contained for now, even if that leads to some duplication.

**Comment by kkocel** [comment]
Ok, I will separate them again then :)

**Comment by kkocel** [comment]
@jfschmakeit Opened another PR with desired changes https://github.com/googlesamples/android-play-safetynet/pull/4

**Pull request closed without merging**
